import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';
import Banner from '@/components/Pages/HomePage/Banner';
import AboutMe from '@/components/Pages/HomePage/AboutMe';
import Services from '@/components/Pages/HomePage/Services';
import Patients from '@/components/Pages/HomePage/Patients';
import WhereToFindMe from '@/components/Pages/HomePage/WhereToFindMe';
import LetsWork from '@/components/Pages/HomePage/LetsWork';

export default function Home() {
	const { t } = useTranslation('common');

	return (
		<>
			<Head>
				<title>Veterinária Carolina Mago</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				{/* <link rel='icon' href='/favicon.ico' /> */}
			</Head>
			<div className="bg-[url('/images/backgroundForest.jpg')] h-screen mt-[-210px] w-screen absolute top-0 -z-10 bg-no-repeat bg-cover bg-top left-0" />
			<div className='w-full h-full'>
				<Banner />
				<AboutMe />
				<WhereToFindMe />
				<Services />
				<Patients />
				<LetsWork />
			</div>
		</>
	);
}

export async function getStaticProps({ locale }: { locale: string }) {
	return {
		props: {
			...(await serverSideTranslations(locale, ['common'])),
		},
	};
}
